apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      kind: Ingress
      name: example
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: www.example.com
      - op: replace
        path: /spec/rules/0/host
        value: www.example.com
